#include <zx/event.h>
ZXSYS ZXEVENT( zxEVENT_onIdle  ) { return zxDefWinEvt; }
ZXSYS ZXEVENT( zxEVENT_onInit  ) { return zxDefWinEvt; }
ZXSYS ZXEVENT( zxEVENT_onKill  ) { return zxDefWinEvt; }
ZXSYS ZXEVENT( zxEVENT_onChar  ) { return zxDefWinEvt; }
ZXSYS ZXEVENT( zxEVENT_onKeyD  ) { return zxDefWinEvt; }
ZXSYS ZXEVENT( zxEVENT_onKeyU  ) { return zxDefWinEvt; }
ZXSYS ZXEVENT( zxEVENT_onCurMV ) { return zxDefWinEvt; }
ZXSYS ZXEVENT( zxEVENT_onCurLD ) { return zxDefWinEvt; }
ZXSYS ZXEVENT( zxEVENT_onCurMD ) { return zxDefWinEvt; }
ZXSYS ZXEVENT( zxEVENT_onCurRD ) { return zxDefWinEvt; }
ZXSYS ZXEVENT( zxEVENT_onCurBD ) { return zxDefWinEvt; }
ZXSYS ZXEVENT( zxEVENT_onCurLU ) { return zxDefWinEvt; }
ZXSYS ZXEVENT( zxEVENT_onCurMU ) { return zxDefWinEvt; }
ZXSYS ZXEVENT( zxEVENT_onCurRU ) { return zxDefWinEvt; }
ZXSYS ZXEVENT( zxEVENT_onCurBU ) { return zxDefWinEvt; }
ZXSYS ZXEVENT( zxEVENT_onCurWH ) { return zxDefWinEvt; }
ZXSYS ZXEVENT( zxEVENT_onFocus ) { return zxDefWinEvt; }
ZXSYS ZXEVENT( zxEVENT_onBlur  ) { return zxDefWinEvt; }
ZXSYS ZXEVENT( zxEVENT_onShow  ) { return zxDefWinEvt; }
ZXSYS ZXEVENT( zxEVENT_onHide  ) { return zxDefWinEvt; }
ZXSYS ZXEVENT( zxEVENT_onMax   ) { return zxDefWinEvt; }
ZXSYS ZXEVENT( zxEVENT_onMin   ) { return zxDefWinEvt; }
ZXSYS ZXEVENT( zxEVENT_onRes   ) { return zxDefWinEvt; }
ZXSYS ZXEVENT( zxEVENT_onShowAct ) { return zxDefWinEvt; }
ZXSYS ZXEVENT( zxEVENT_onHideAct ) { return zxDefWinEvt; }
ZXSYS ZXEVENT( zxEVENT_onMaxAct  ) { return zxDefWinEvt; }
ZXSYS ZXEVENT( zxEVENT_onMinAct  ) { return zxDefWinEvt; }
ZXSYS ZXEVENT( zxEVENT_onResAct  ) { return zxDefWinEvt; }
ZXSYS ZXEVENT( zxEVENT_onShowNoa ) { return zxDefWinEvt; }
ZXSYS ZXEVENT( zxEVENT_onHideNoa ) { return zxDefWinEvt; }
ZXSYS ZXEVENT( zxEVENT_onMaxNoa  ) { return zxDefWinEvt; }
ZXSYS ZXEVENT( zxEVENT_onMinNoa  ) { return zxDefWinEvt; }
ZXSYS ZXEVENT( zxEVENT_onResNoa  ) { return zxDefWinEvt; }
ZXSYS ZXEVENT( zxEVENT_onOpen ) { return zxDefWinEvt; }
ZXSYS ZXEVENT( zxEVENT_onShut ) { return zxDefWinEvt; }
ZXSYS ZXEVENT( zxEVENT_onQuit ) { return zxDefWinEvt; }